# Generated by Django 5.2 on 2025-05-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myytavat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myytavat',
            new_name='Myytava',
        ),
    ]
