# Generated by Django 5.2 on 2025-05-07 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myytavat', '0002_rename_myytavat_myytava'),
        ('posts', '0018_rename_myytava_kpl'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateMyytava',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
            ],
            bases=('posts.post',),
        ),
    ]
