# Generated by Django 5.2 on 2025-05-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myytavat', '0003_createmyytava'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateMyytava',
        ),
    ]
