# Generated by Django 5.2.1 on 2025-05-14 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aika', models.CharField(choices=[('16.30', '16.30'), ('17.00', '17.00'), ('17.30', '17.30'), ('18.00', '18.00')], default='16.30', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Artikkeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikkeli', models.CharField(max_length=75)),
                ('hinta', models.FloatField(default=0)),
                ('lisatietoja', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Kpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Taloyhtio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('taloyhtio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asunnot', to='artikkelit.taloyhtio')),
            ],
        ),
    ]
