# Generated by Django 5.2 on 2025-05-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aika', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Ruoka-ajat',
            },
        ),
        migrations.CreateModel(
            name='Artikkeli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikkeli', models.CharField(max_length=75)),
                ('hinta', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('lisatietoja', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'Artikkelit',
            },
        ),
        migrations.CreateModel(
            name='Myynti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpl', models.IntegerField(blank=True)),
                ('aika', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikkelit.aika')),
                ('artikkeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artikkelit.artikkeli')),
            ],
            options={
                'verbose_name_plural': 'Myynnit',
            },
        ),
    ]
