# Generated by Django 5.2.1 on 2025-05-28 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asunto',
            options={'verbose_name_plural': 'Asunnot'},
        ),
        migrations.AlterModelOptions(
            name='taloyhtio',
            options={'verbose_name_plural': 'Taloyhtiot'},
        ),
        migrations.AlterField(
            model_name='asunto',
            name='taloyhtio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='artikkelit.taloyhtio'),
        ),
        migrations.AlterField(
            model_name='taloyhtio',
            name='taloyhtio',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.DeleteModel(
            name='Taloyhtiovalinta',
        ),
    ]
