# Generated by Django 5.2.1 on 2025-05-21 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aika',
            options={'verbose_name_plural': 'Ruoka-ajat'},
        ),
    ]
