# Generated by Django 5.2.1 on 2025-05-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aika',
            name='aika',
            field=models.CharField(max_length=5),
        ),
    ]
