# Generated by Django 5.2 on 2025-05-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aika',
            name='aika',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
