# Generated by Django 5.2.1 on 2025-06-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asunto',
            name='taloyhtio',
        ),
    ]
