# Generated by Django 5.2.1 on 2025-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myynti',
            name='kateismyynti',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
