# Generated by Django 5.2 on 2025-05-23 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myynti',
            name='aika',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikkelit.aika'),
        ),
    ]
