# Generated by Django 5.2.1 on 2025-05-21 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myynti',
            name='alle_3v',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='extra_burger',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='gluteeniton',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='kasvis',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='maidoton',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='taloyhtio',
        ),
        migrations.RemoveField(
            model_name='myynti',
            name='vegaaninen',
        ),
    ]
