# Generated by Django 5.2.1 on 2025-06-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0002_remove_asunto_taloyhtio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asunto',
            name='taloyhtio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikkelit.taloyhtio'),
        ),
    ]
