# Generated by Django 5.2 on 2025-05-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0002_alter_aika_aika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aika',
            name='aika',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
