# Generated by Django 5.2.1 on 2025-06-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikkeli',
            name='lisatietoja',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
