# Generated by Django 5.2 on 2025-05-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0002_myynti_aika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myynti',
            name='kpl',
            field=models.IntegerField(blank=True),
        ),
    ]
