# Generated by Django 5.2.1 on 2025-06-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0002_alter_asunto_options_alter_taloyhtio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myynti',
            name='asunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikkelit.asunto'),
        ),
        migrations.AddField(
            model_name='myynti',
            name='taloyhtio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artikkelit.taloyhtio'),
        ),
    ]
