# Generated by Django 5.2 on 2025-05-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0003_alter_myynti_kpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aika',
            name='aika',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
