# Generated by Django 5.2.1 on 2025-06-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0003_asunto_taloyhtio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asunto',
            old_name='nimi',
            new_name='asunto',
        ),
        migrations.RenameField(
            model_name='taloyhtio',
            old_name='nimi',
            new_name='taloyhtio',
        ),
    ]
