# Generated by Django 5.2.1 on 2025-06-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0004_rename_nimi_asunto_asunto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asunto',
            old_name='asunto',
            new_name='nimi',
        ),
        migrations.RenameField(
            model_name='taloyhtio',
            old_name='taloyhtio',
            new_name='nimi',
        ),
    ]
