# Generated by Django 5.2.1 on 2025-06-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0005_rename_asunto_asunto_nimi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myynti',
            name='kpl',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
