# Generated by Django 5.2.1 on 2025-06-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0006_alter_myynti_kpl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myynti',
            name='kpl',
            field=models.IntegerField(blank=True, max_length=5),
        ),
    ]
