# Generated by Django 5.2.1 on 2025-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikkelit', '0013_alter_myynti_kateismyynti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myynti',
            name='kpl',
            field=models.IntegerField(blank=True, choices=[(10, '10 kpl'), (2, '2 kpl'), (9, '9 kpl'), (8, '8 kpl'), (6, '6 kpl'), (7, '7 kpl'), (4, '4 kpl'), (3, '3 kpl'), (5, '5 kpl'), (1, '1 kpl')], default=1),
        ),
    ]
