# Generated by Django 5.2 on 2025-04-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hinta',
            field=models.FloatField(default=0),
        ),
    ]
