# Generated by Django 5.2 on 2025-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_hinta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artikkeli',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
