# Generated by Django 5.2 on 2025-05-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_artikkeli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artikkeli',
        ),
    ]
