# Generated by Django 5.2 on 2025-05-02 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_artikkeli'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='artikkeli',
        ),
    ]
