# Generated by Django 5.2 on 2025-05-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lisatietoja',
            field=models.CharField(),
        ),
    ]
