# Generated by Django 5.2 on 2025-05-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_lisatietoja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='index',
        ),
    ]
