# Generated by Django 5.2 on 2025-05-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_id_post_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='index',
            new_name='paikka',
        ),
    ]
