# Generated by Django 5.2 on 2025-05-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_rename_index_post_paikka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='paikka',
        ),
        migrations.AddField(
            model_name='post',
            name='artikkeli_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vuosi',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
