# Generated by Django 5.2 on 2025-05-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_paikka_post_artikkeli_id_post_vuosi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vuosi',
        ),
    ]
