# Generated by Django 5.2 on 2025-05-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_vuosi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='artikkeli_id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
