# Generated by Django 5.2 on 2025-05-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_artikkeli_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('artikkeli_id', models.CharField(primary_key=True, serialize=False)),
                ('artikkeli', models.CharField(max_length=75)),
                ('hinta', models.FloatField(default=0)),
                ('lisatietoja', models.CharField()),
            ],
        ),
    ]
