# Generated by Django 5.2 on 2025-05-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_node'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myytava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpl', models.IntegerField()),
            ],
        ),
    ]
