# Generated by Django 5.2 on 2025-05-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_myytava'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myytava',
            new_name='Kpl',
        ),
    ]
