# Generated by Django 5.2 on 2025-05-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_myytava_kpl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='artikkeli_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='artikkeli_id',
        ),
        migrations.AddField(
            model_name='node',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
