# Generated by Django 5.2 on 2025-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_node_artikkeli_id_remove_post_artikkeli_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='aika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
