# Generated by Django 5.2 on 2025-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_aika'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='aika',
            name='aika',
            field=models.CharField(choices=[('AIKA1', '16.30'), ('AIKA2', '17.00'), ('AIKA3', '17.30'), ('AIKA4', '18.00')], default=5, max_length=5),
            preserve_default=False,
        ),
    ]
