# Generated by Django 5.2 on 2025-05-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_delete_node_aika_aika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aika',
            name='aika',
            field=models.CharField(choices=[('16.30', '16.30'), ('17.00', '17.00'), ('17.30', '17.30'), ('18.00', '18.00')], default='16.30', max_length=5),
        ),
    ]
