# Generated by Django 5.2 on 2025-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_aika_aika'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaloyhtiotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taloyhtio', models.CharField(choices=[('AATELITIE_3', 'Aatelitie_3'), ('AATELITIE_5_7', 'Aatelitie_5_7'), ('AATELISHERRA', 'Aatelisherra'), ('AATELISROUVA', 'Aatelisrouva'), ('RENKIPOIKA', 'Renkipoika'), ('PIIKATYTTO', 'Piikatytto'), ('OMAKOTITALOT', 'Omakotitalot')], max_length=30)),
            ],
        ),
    ]
