# Generated by Django 5.2.1 on 2025-05-12 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_taloyhtiotmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Taloyhtio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='TaloyhtiotModel',
        ),
        migrations.AddField(
            model_name='asunto',
            name='taloyhtio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='posts.taloyhtio'),
        ),
    ]
